### PR TITLE
Add support for Youtube hash start times

### PR DESCRIPTION
**Pull request by mpatnode**
Fun found digging through Google Console errors

http://www.popsugar.com/moms/Groom-Reads-Vows-His-Stepdaughter-His-Wedding-36965836/amp

### CODE REVIEW

**Comment by obeyer** [comment]
I thought we are extending classes and not editing vendor's code. why don't you want to create something like SugarIframeYouTubeTagTransformPass.php ?

**Comment by mpatnode** [comment]
Too much cut & paste.  When vendor code is obviously broken, we should fix it.

**Comment by obeyer** [comment]
but it is not about broken. I agree it has some flaws. what if they decide to update it, and then how are we gonna update ours? all our changes will be gone if they done in vendor files

**Comment by mpatnode** [comment]
What if their update breaks object inheritance?  I've been working with Open Source projects for 30 years.  When upstream changes, you merge the changes you want into your code.   Sometimes you don't want the changes.   What do we do then?  This project is not like mysql, nginx or codeception.   It does not have a large following and it's not even clear it's still active.   Nor do are we forced to apply a single methodology to every Open Source project we use.    This code is in the critical path for our site, let's not be afraid to improve it or make it more difficult to do so than necessary.   @casey-powell @kkopachev

**Comment by casey-powell** [comment]
In this case it seems like it would not be that big of a deal to extend the class and override the functions in question. My vote is extend when possible and fork when not. This makes it easier for us to see what exactly we have changed, as well as keeping path to upgrade simpler. Just my $0.02

**Comment by ChrisHawley** [comment]
I think this change makes sense in `IframeYouTubeTagTransformPass` (rather than in some subclass) because to me this feels like a feature that all users of this library would expect to be available by default.

To deal with the upstream issue that @obeyer pointed out, @mpatnode-si are you planning on opening a PR to Lullabot/amp-library with this change? (I should do the same with my change from last night).

**Pull request merged**
